project_id = "hjorsjoaykgnsmbxgnyn"

[functions.bible-chat]
verify_jwt = false

[functions.generate-certificate-pdf]
verify_jwt = false

[functions.translate-strongs]
verify_jwt = false

[functions.translate-strongs-batch]
verify_jwt = true
